services:
  php:
    build: .
    container_name: php-app
    volumes:
      - ./app/public:/var/www/html
      - ./app/src:/var/www/src
      - ./app/config:/var/www/config
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: quizapp
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    ports:
      - "3306:3306"
